apiVersion: v1
kind: Service
metadata:
  name: ms-usuariocliente
  namespace: backend
spec:
  type: NodePort
  selector:
    app: ms-usuariocliente
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
      nodePort: 30084   # Puerto externo accesible
  # loadbalancer
