apiVersion: v1
kind: Service
metadata:
  name: ms-usuariocliente
spec:
  selector:
    app: ms-usuariocliente
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
  type: ClusterIP 
  # loadbalancer
