version: '3.8'

services:
  inicio:
    build:
      context: ./inicio
    ports:
      - "8081:80"

  ms-farmacia:
    build:
      context: ./ms-farmacia
    ports:
      - "8082:80"

  ms-inventario:
    build:
      context: ./ms-inventario
    ports:
      - "8083:80"

  ms-trabajador:
    build:
      context: ./ms-trabajador
    ports:
      - "8084:80"

  ms-usuariocliente:
    build:
      context: ./ms-usuariocliente
    ports:
      - "8085:80"

  ms-venta:
    build:
      context: ./ms-venta
    ports:
      - "8086:80"
