services:
  db_hola_mundo:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "54321:5432"
    volumes:
      - ./ms-holamundo/db/db_hola_mundo.sql:/docker-entrypoint-initdb.d/init.sql
  hola_mundo:
    build:
      context: ./ms-holamundo
      dockerfile: Dockerfile
    container_name: api-ms-holamundo
    ports:
      - "80010:8000"
    depends_on:
      db_hola_mundo:
        condition: service_started

  db_inventario:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "54321:5432" # 5432 puerto base - 2 puerto para inventario
    volumes:
      - ./ms/inventario/db/db_inventario.sql:/docker-entrypoint-initdb.d/init.sql
  inventario:
    build:
      context: ./ms-inventario
      dockerfile: Dockerfile
    container_name: api-ms-inventario
    ports:
      - "80011:8000"
    depends_on:
      db_inventario:
        condition: service_started