services:
  db_inventario:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      #POSTGRES_DB: inventario
    ports:
      - "54322:5432" # 5432 puerto base - 2 puerto para inventario
    volumes:
      - ./db/db-inventario/db_inventario.sql:/docker-entrypoint-initdb.d/init.sql
  inventario:
    build:
      context: ./ms-inventario
      dockerfile: Dockerfile
    container_name: api-ms-inventario
    ports:
      - "8002:8000"
    depends_on:
      db_inventario:
        condition: service_started
  
  db_cliente:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "54324:5432" # 5432 puerto base - 3 puerto para cliente
    volumes:
      - ./db/db-usuariocliente/db_usuariocliente.sql:/docker-entrypoint-initdb.d/init.sql
  
  usuariocliente:
    build:
      context: ./ms-usuariocliente
      dockerfile: Dockerfile
    container_name: api-ms-usuariocliente
    ports:
      - "8004:8000"
    depends_on:
      db_cliente:
        condition: service_started