# version: '3.8'

# services:
#   db_inventario:
#     image: postgres:13
#     environment:
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: secret
#     ports:
#       - "54322:5432"
#     volumes:
#       - ./db/db-inventario/db_inventario.sql:/docker-entrypoint-initdb.d/init.sql

#   inventario:
#     build:
#       context: ./ms-inventario
#       dockerfile: Dockerfile
#     container_name: api-ms-inventario
#     ports:
#       - "8002:8081"
#     depends_on:
#       db_inventario:
#         condition: service_started
#     restart: on-failure

#   db_trabajador:
#     image: postgres:13
#     environment:
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: secret
#     ports:
#       - "54323:5432"
#     volumes:
#       - ./db/db-trabajador/db_trabajador.sql:/docker-entrypoint-initdb.d/init.sql

#   trabajador:
#     build:
#       context: ./ms-trabajador
#       dockerfile: Dockerfile
#     container_name: api-ms-trabajador
#     ports:
#       - "8003:8082"
#     depends_on:
#       db_trabajador:
#         condition: service_started
#     restart: on-failure

#   db_farmacia:
#     image: postgres:13
#     environment:
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: secret
#     ports:
#       - "54326:5432"
#     volumes:
#       - ./db/db-farmacia/db_farmacia.sql:/docker-entrypoint-initdb.d/init.sql

#   farmacia:
#     build:
#       context: ./ms-farmacia
#       dockerfile: Dockerfile
#     container_name: api-ms-farmacia
#     ports:
#       - "8006:8080"
#     depends_on:
#       db_farmacia:
#         condition: service_started
#     restart: on-failure

#   db_cliente:
#     image: postgres:13
#     environment:
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: secret
#     ports:
#       - "54324:5432"
#     volumes:
#       - ./db/db-usuariocliente/db_usuariocliente.sql:/docker-entrypoint-initdb.d/init.sql

#   usuariocliente:
#     build:
#       context: ./ms-usuariocliente
#       dockerfile: Dockerfile
#     container_name: api-ms-usuariocliente
#     ports:
#       - "8004:8083"
#     depends_on:
#       db_cliente:
#         condition: service_started
#     restart: on-failure

#   db_venta:
#     image: postgres:13
#     environment:
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: secret
#     ports:
#       - "54325:5432"
#     volumes:
#       - ./db/db-venta/db_venta.sql:/docker-entrypoint-initdb.d/init.sql

#   venta:
#     build:
#       context: ./ms-venta
#       dockerfile: Dockerfile
#     container_name: api-ms-venta
#     ports:
#       - "8005:8084"
#     depends_on:
#       db_venta:
#         condition: service_started
#     restart: on-failure


version: '3.8'

services:
  db_inventario:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "54322:5432"
    volumes:
      - ./db/db-inventario/db_inventario.sql:/docker-entrypoint-initdb.d/init.sql

  inventario:
    build:
      context: ./ms-inventario
      dockerfile: Dockerfile
    container_name: api-ms-inventario
    ports:
      - "8002:8081"
    depends_on:
      db_inventario:
        condition: service_started
    restart: on-failure
    environment:
      DB_NAME: inventario
      DB_USER: admin
      DB_PASSWORD: secret
      DB_HOST: db_inventario
      DB_PORT: 5432

  db_trabajador:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "54323:5432"
    volumes:
      - ./db/db-trabajador/db_trabajador.sql:/docker-entrypoint-initdb.d/init.sql

  trabajador:
    build:
      context: ./ms-trabajador
      dockerfile: Dockerfile
    container_name: api-ms-trabajador
    ports:
      - "8003:8082"
    depends_on:
      db_trabajador:
        condition: service_started
    restart: on-failure
    environment:
      DB_NAME: trabajadores
      DB_USER: admin
      DB_PASSWORD: secret
      DB_HOST: db_trabajador
      DB_PORT: 5432

  db_farmacia:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "54326:5432"
    volumes:
      - ./db/db-farmacia/db_farmacia.sql:/docker-entrypoint-initdb.d/init.sql

  farmacia:
    build:
      context: ./ms-farmacia
      dockerfile: Dockerfile
    container_name: api-ms-farmacia
    ports:
      - "8006:8080"
    depends_on:
      db_farmacia:
        condition: service_started
    restart: on-failure
    environment:
      DB_NAME: farmacias
      DB_USER: admin
      DB_PASSWORD: secret
      DB_HOST: db_farmacia
      DB_PORT: 5432

  db_cliente:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "54324:5432"
    volumes:
      - ./db/db-usuariocliente/db_usuariocliente.sql:/docker-entrypoint-initdb.d/init.sql

  usuariocliente:
    build:
      context: ./ms-usuariocliente
      dockerfile: Dockerfile
    container_name: api-ms-usuariocliente
    ports:
      - "8004:8083"
    depends_on:
      db_cliente:
        condition: service_started
    restart: on-failure
    environment:
      DB_NAME: usuarios_farmacia
      DB_USER: admin
      DB_PASSWORD: secret
      DB_HOST: db_cliente
      DB_PORT: 5432

  db_venta:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "54325:5432"
    volumes:
      - ./db/db-venta/db_venta.sql:/docker-entrypoint-initdb.d/init.sql

  venta:
    build:
      context: ./ms-venta
      dockerfile: Dockerfile
    container_name: api-ms-venta
    ports:
      - "8005:8084"
    depends_on:
      db_venta:
        condition: service_started
    restart: on-failure
    environment:
      DB_NAME: venta
      DB_USER: admin
      DB_PASSWORD: secret
      DB_HOST: db_venta
      DB_PORT: 5432
