services:
  db_inventario:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "54322:5432" # 5432 puerto base - 2 puerto para inventario
    volumes:
      - ./db/db-inventario/db_inventario.sql:/docker-entrypoint-initdb.d/init.sql
  
  inventario:
    build:
      context: ./ms-inventario
      dockerfile: Dockerfile
    container_name: api-ms-inventario
    ports:
      - "8002:8000"
    depends_on:
      db_inventario:
        condition: service_started
  
  db_trabajador:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "54323:5432" # 5432 puerto base - 3 puerto para trabajador
    volumes:
      - ./db/db-trabajador/db_trabajador.sql:/docker-entrypoint-initdb.d/init.sql
  
  trabajador:
    build:
      context: ./ms-trabajador
      dockerfile: Dockerfile
    container_name: api-ms-trabajador
    ports:
      - "8003:8000"
    depends_on:
      db_trabajador:
        condition: service_started

  db_farmacia:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "54326:5432" # 5432 puerto base - 3 puerto para farmacia
    volumes:
      - ./db/db-farmacia/db_farmacia.sql:/docker-entrypoint-initdb.d/init.sql

  farmacia:
    build:
      context: ./ms-farmacia
      dockerfile: Dockerfile
    container_name: api-ms-farmacia
    ports:
      - "8006:8000"
    depends_on:
      db_farmacia:
        condition: service_started