services:
  db_hola_mundo:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - ./db/db_hola_mundo.sql:/docker-entrypoint-initdb.d/init.sql
  hola_mundo:
    build:
      context: ./ms-holamundo
      dockerfile: Dockerfile
    container_name: api-ms-holamundo
    ports:
      - "8000:8000"
    depends_on:
      db_hola_mundo:
        condition: service_started
    inventario:
      build:
        context: ./ms-inventario
        dockerfile: Dockerfile
      container_name: api-ms-inventario
      ports:
        - "8001:8000"
      depends_on:
        db_inventario:
          condition: service_started