apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-venta
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-venta
  template:
    metadata:
      labels:
        app: ms-venta
    spec:
      containers:
        - name: ms-venta
          image: "diegoarteagamendoza2002/ms-venta:1.0.1"
          ports:
            - containerPort: 8005
