apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000       # Puerto del servicio dentro del clúster
      targetPort: 3000 # Puerto del contenedor de Grafana
  type: NodePort       # Para acceder a Grafana desde tu máquina vía Minikube