apiVersion: v1
kind: Service
metadata:
  name: ms-inventario-frontend
spec:
  selector:
    app: ms-inventario-frontend
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
