apiVersion: v1
kind: Service
metadata:
  name: ms-inventario-frontend
spec:
  selector:
    app: ms-inventario-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
