apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-trabajador
  labels:
    app: ms-trabajador
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-trabajador
  template:
    metadata:
      labels:
        app: ms-trabajador
    spec:
      containers:
        - name: ms-trabajador
          image: "diegoarteagamendoza2002/ms-trabajador:1.0.0"
          ports:
            - containerPort: 8009
