apiVersion: v1
kind: Service
metadata:
  name: ms-trabajador
spec:
  selector:
    app: ms-trabajador
  ports:
    - protocol: TCP
      port: 8008
      targetPort: 8009
  type: ClusterIP 
  # loadbalancer
