apiVersion: v1
kind: Service
metadata:
  name: db-farmacia
  namespace: database
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 54326
      targetPort: 54326
      nodePort: 30436
