version: '3.8'

services:
  proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - inicio
      - ms-farmacia
      - ms-inventario
      - ms-trabajador
      - ms-usuariocliente
      - ms-venta

  inicio:
    build:
      context: ./inicio
    container_name: inicio

  ms-farmacia:
    build:
      context: ./ms-farmacia
    container_name: ms-farmacia

  ms-inventario:
    build:
      context: ./ms-inventario
    container_name: ms-inventario

  ms-trabajador:
    build:
      context: ./ms-trabajador
    container_name: ms-trabajador

  ms-usuariocliente:
    build:
      context: ./ms-usuariocliente
    container_name: ms-usuariocliente

  ms-venta:
    build:
      context: ./ms-venta
    container_name: ms-venta
