# apiVersion: v1
# kind: Service
# metadata:
#   name: ms-inventario
# spec:
#   selector:
#     app: ms-inventario
#   ports:
#     - protocol: TCP
#       port: 8000
#       targetPort: 8000
#   type: ClusterIP 
#   # loadbalancer

apiVersion: v1
kind: Service
metadata:
  name: ms-inventario-svc
  namespace: backend
spec:
  type: NodePort
  selector:
    app: ms-inventario
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
      nodePort: 30082   # Puerto externo accesible
