apiVersion: v1
kind: Service
metadata:
  name: ms-inventario
  labels:
    app: ms-inventario
spec:
  selector:
    app: ms-inventario
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP 
  # loadbalancer
