apiVersion: v1
kind: Service
metadata:
  name: ms-farmacia
spec:
  selector:
    app: ms-farmacia
  ports:
    - protocol: TCP
      port: 8006
      targetPort: 8006
  type: ClusterIP 
  # loadbalancer
