apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials-inventario
  namespace: database
type: Opaque
data:
  username: YWRtaW4=       # "admin" en base64
  password: c2VjcmV0   # "secret" en base64
