apiVersion: v1
kind: Service
metadata:
  name: db-inventario
  namespace: database
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 54322
      targetPort: 54322
      nodePort: 30432
