apiVersion: v1
kind: Service
metadata:
  name: db-venta
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 54325
      targetPort: 54325
      nodePort: 30432
