name: Backend CI - db-trabajador

on:
  push:
    branches: [main]
    paths:
      - 'backend/db/db-trabajador/**'
  pull_request:
    branches: [main]
    paths:
      - 'backend/db/db-trabajador/**'

jobs:
  build-and-deploy-trabajador:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        microservice: [db-trabajador]

    env:
      DOCKER_REPO: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Iniciar sesión en Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Construir la imagen de Docker
        run: |
          IMAGE_NAME=${{ env.DOCKER_REPO }}/${{ matrix.microservice }}:latest
          docker build -t $IMAGE_NAME backend/db/${{ matrix.microservice }}

      - name: Enviar la imagen a Docker Hub
        run: |
          IMAGE_NAME=${{ env.DOCKER_REPO }}/${{ matrix.microservice }}:latest
          docker push $IMAGE_NAME