name: Backend CI - ms-holamundo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy-holamundo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        microservice: [ms-holamundo]

    env:
      DOCKER_REPO: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Leer versión del archivo VERSION
        id: version
        run: |
          echo "VERSION=$(cat backend/${{ matrix.microservice }}/VERSION)" >> $GITHUB_ENV

      - name: Iniciar sesión en Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Construir la imagen de Docker con la versión
        run: |
          IMAGE_NAME=${{ env.DOCKER_REPO }}/${{ matrix.microservice }}:${{ env.VERSION }}
          docker build -t $IMAGE_NAME backend/${{ matrix.microservice }}

      - name: Enviar la imagen a Docker Hub
        run: |
          IMAGE_NAME=${{ env.DOCKER_REPO }}/${{ matrix.microservice }}:${{ env.VERSION }}
          docker push $IMAGE_NAME
